name: NocoBase backend test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'base branch'
        required: true
      nocobase_pr_number:
        description: 'main repo pr number'
      pro_repo:
        description: 'pro repository name'
        default: 'pro-plugins'
      pro_pr_number:
        description: 'pro repo pr number'
      checkRunId:
        description: 'check run id'

jobs:
  backend-test:
    strategy:
      fail-fast: false
      matrix:
        node_version: ['20']
        db:
          - dialect: sqlite
            host: localhost
            port: ''
          - dialect: mysql
            host: mysql
            port: 3306
          - dialect: mariadb
            host: mariadb
            port: 3306
          - dialect: postgres
            host: postgres
            port: 5432
          - dialect: postgres
            host: postgres
            port: 5432
            env:
              - DB_SCHEMA: nocobase
          - dialect: postgres
            host: postgres
            port: 5432
            env:
              - COLLECTION_MANAGER_SCHEMA: user_schema
          - dialect: postgres
            host: postgres
            port: 5432
            env:
              - DB_SCHEMA: nocobase
              - COLLECTION_MANAGER_SCHEMA: user_schema
        underscored: [true, false]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: nocobase
        options: --health-cmd="mysqladmin ping" --health-interval=20s --health-timeout=10s --health-retries=5
      mariadb:
        image: mariadb:10.9
        env:
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: nocobase
        options: --health-cmd="mysqladmin ping" --health-interval=20s --health-timeout=10s --health-retries=5
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nocobase
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      REMOTE_MYSQL_HOST: mysql
      REMOTE_MYSQL_PORT: 3306
      REMOTE_MYSQL_USER: root
      REMOTE_MYSQL_PASSWORD: password
      REMOTE_MYSQL_DB: nocobase

      REMOTE_MARIADB_HOST: mariadb
      REMOTE_MARIADB_PORT: 3306
      REMOTE_MARIADB_USER: root
      REMOTE_MARIADB_PASSWORD: password
      REMOTE_MARIADB_DB: nocobase

      REMOTE_POSTGRES_HOST: postgres
      REMOTE_POSTGRES_PORT: 5432
      REMOTE_POSTGRES_USER: root
      REMOTE_POSTGRES_PASSWORD: password
      REMOTE_POSTGRES_DB: nocobase

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.NOCOBASE_APP_ID }}
          private-key: ${{ secrets.NOCOBASE_APP_PRIVATE_KEY }}
          owner: nocobase
          repositories: nocobase,pro-plugins,${{ inputs.pro_repo }}
          skip-token-revoke: true
      - name: Git safe directory
        run: git config --global --add safe.directory `pwd`
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: nocobase/nocobase
          ref: ${{ inputs.branch }}
          token: ${{ steps.app-token.outputs.token }}
          submodules: true
      - name: Checkout nocobase/nocobase pr
        if: ${{ inputs.nocobase_pr_number != '' }}
        shell: bash
        run: |
          gh pr checkout ${{ inputs.nocobase_pr_number }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Checkout pro-plugins
        uses: actions/checkout@v3
        if: ${{ inputs.pro_repo == 'pro-plugins' || !inputs.pro_repo }}
        with:
          repository: nocobase/pro-plugins
          ref: ${{ inputs.branch }}
          path: packages/pro-plugins
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Checkout pro-plugins pr
        if: ${{ (inputs.pro_repo == 'pro-plugins' || !inputs.pro_repo) && inputs.pro_pr_number != '' }}
        shell: bash
        run: |
          cd ./packages/pro-plugins/
          gh pr checkout ${{ inputs.pro_pr_number }}
          cd ../../
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Checkout pro repo
        uses: actions/checkout@v3
        if: ${{ inputs.pro_repo != 'pro-plugins' && inputs.pro_repo }}
        with:
          repository: nocobase/${{ inputs.pro_repo }}
          ref: ${{ inputs.branch }}
          path: packages/pro-plugins/@nocobase/${{ inputs.pro_repo }}
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Checkout pro repo pr
        if: ${{ inputs.pro_repo != 'pro-plugins' && inputs.pro_pr_number != '' }}
        shell: bash
        run: |
          cd ./packages/pro-plugins/@nocobase/${{ inputs.pro_repo }}
          gh pr checkout ${{ inputs.pro_pr_number }}
          cd ../../../../
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn install
      - name: Run test
        run: |
          yarn test --server packages/pro-plugins/@nocobase 
        env:
          LOGGER_LEVEL: error
          ENCRYPTION_FIELD_KEY: '66036232662082160067048057423456'
          DB_DIALECT: ${{ matrix.db.dialect }}
          DB_HOST: ${{ matrix.db.host }}
          DB_PORT: ${{ matrix.db.port }}
          DB_STORAGE: /tmp/db.sqlite
          DB_USER: root
          DB_PASSWORD: password
          DB_DATABASE: nocobase
          DB_UNDERSCORED: ${{ matrix.underscored }}

